### PR TITLE
Move custom_fields to AbstractRequest, update to java 8

### PR DESCRIPTION
**Pull request by jspaetzel**
For #96

### CODE REVIEW

**Comment by codylerum** [comment]
@jspaetzel Where should the customFields be added? I have them being added to the embedded request as before and they aren't getting added to the post for HelloSignClient#createEmbeddedRequest

**Comment by codylerum** [comment]
@jspaetzel OK after some debugging I see I need to add it to the SignatureRequest. I've tested that and it apppears to be working ok and posting the customField with the request. Signature request 8901280b07fa2632b5c1620579de529008137300 if you are interested.

I think you are good to roll merge this in.

**Comment by jspaetzel** [comment]
@codylerum I went ahead and added support so that it can be added to the embedded request or unclaimed draft as well. Feel free to use it either way, i'll roll this in shortly.

**Comment by codylerum** [comment]
@jspaetzel Thanks. As I look at my code I think it makes the most sense to add the custom fields to the signature request object. Nice to have options though.

**Comment by jspaetzel** [comment]
I'll push this to central as 4.1.0 a bit later today once I make a few more changes.

**Pull request merged**
